### ISSUE TITLE
Fix or support return ref value

### ISSUE THREAD

**Issue by quifi** [dadhi/FastExpressionCompiler#415]
With C#, we can return a ref value:
```
ref Int32 ReturnByRef(ref Int32 x) => ref x;
```
System expression simply says it is not supported
```
System.ArgumentException : Expression of type 'System.Int32' cannot be used for return type 'System.Int32&'
```
LightExpression supports return ref value, but sometimes fails to unref returned ref value.
e.g.
```
Int32 f(ref Int32 x) => ReturnByRef(ref x);
```
emits
```
ldarg.1
call Int32& ReturnRef(Int32 ByRef)
(missing ldind.i4)
ret
```
See the "ReadReturnedRef" test case of attached source file.
[ReturnRef.zip](https://github.com/user-attachments/files/15891456/ReturnRef.zip)

I tried to add a `EmitLoadIndirectlyByRef` after each `Demit(OpCodes.Call)`, which seemed worked.

**Comment by dadhi** [comment]
@quifi Thank you for the reporting and for the 2 other issues

**Comment by dadhi** [comment]
@quifi I have checked your sample, but I don't see `ldind.i4` in the [decompiled IL code](https://sharplab.io/#v2:C4LglgNgPgsAUAAQMwAIECYUGEUG94qFqoBOApgGYpgB2wKAYgPZMAU5Vt9AHgJR4EiQhAHYUHFNwDchQYQC+coSiXI0ARgBs4ytTooASmWABXEjSMV2urpP4BeAHw6q0patI39AIQCGJa059PhQnJSEJI1NzS0C7KXh5IA=)

So the current FEC output is fine, I think.

**Comment by dadhi** [comment]
@quifi The new FEC v4.2.1 with the fixes is released.

**Comment by quifi** [comment]
> FEC

In order to reproduce the bug, I think 'Bar' should return int, instead of int&.
See [modified sample code](https://sharplab.io/#v2:C4LglgNgPgsAUAAQMwAIECYUGEUG94qFqoBOApgGYpgB2wKAYgPZMAU5Vt9AHgJR4EiQhAHYUHFNwDchQYQC+coSiXI0ARgBs4ytTooASmWABXEjSMV2urpP4BeAHw6q0patS2AQgEMS1zn0+FCclISNTc0sAuyl4eSA)

With v4.2.1, this one seems not fixed yet.
